### ISSUE TITLE
Reconstruct lower and upper bound in image space

### ISSUE THREAD

**Issue by matthewyccheung** [omerb01/puq#1]
Hello! Thanks for the great work and neat code base. How do can we reconstruct lower and upper bound of images? I can't seem to figure it out with all the patches and transforms going on.

**Comment by omerb01** [comment]
Hey @matthewyccheung ! Thank you for asking this relevant question.

In this work, we insist that the conventional paradigm of lower and upper bound images is not applicable because the concept of a "range of solution" does not hold between them within the image domain. This is due to the fact that the intervals were constructed around the principal components axes.
In contrast, the pixelwise approach constructs intervals around each individual pixel. Thus, working with lower and upper bounds in this context makes sense, as the notion of a "range of solution" is correct between these bounds within the image domain. However, our approach results in fewer axes of uncertainty that incorporate semantic factors. This characteristic significantly enhances interpretability and understanding of the uncertainty.

I recommend to adopt a visualization approach for the uncertainty regions similar to that presented in Figure 10 of our paper. It should include individual visualizations of the uncertainty axes.

After saying that, now I'll provide you the code to compute everything (see run.py), including the "lower" and "upper" bound images:
```
puq = DAPUQUncertaintyRegion(args)
# .... Calibration code here (see run.py) ....

test_samples_dataset = DiffusionSamplesDataset(
    opt=args,
    calibration=False,
    transform=T.ToTensor()
)

K = test_samples_dataset.num_samples_per_image
samples_dataloader = torch.utils.data.DataLoader(
    test_samples_dataset,
    batch_size=K * args.batch,
    num_workers=args.num_workers,
    shuffle=False,
    collate_fn=None if args.patch_res is None else misc.concat_patches_samples
)

device = torch.device(f'cuda:{args.gpu}' if args.gpu is not None else 'cpu')
for samples in samples_dataloader:
    samples = samples.view(samples.shape[0]//K, K, -1).to(device)
    batch_mu, batch_pcs, batch_svs, batch_lower, batch_upper = puq.inference(samples)
    for i in range(args.batch):
        mu, pcs, svs, lower, upper = batch_mu[i], batch_pcs[i], batch_svs[i], batch_lower[i], batch_upper[i]

        image_shape = [3, 128, 128]
        lower_bound_image = (mu + pcs @ lower).view(image_shape)
        upper_bound_image = (mu + pcs @ upper).view(image_shape)
        for axis_i in range(pcs.shape[1]):
            axis = pcs[:,axis_i]
            axis_image = axis.view(image_shape).pow(2).sum(dim=0, keepdim=True).sqrt()
```

`lower_bound_image` and `upper_bound_image` is what you looked for.
`axis_image` is what I suggested.

Hope this helps, I'll add this code later to the repository and will fix some bugs that I tracked.
Omer.

**Comment by omerb01** [comment]
@matthewyccheung, my apologies for the delay in the repository update. I've made some improvements to the repository to offer a more user-friendly interface. Additionally, I've included a demonstration of how to use our codebase in [demo.ipynb](https://github.com/omerb01/puq/blob/main/demo.ipynb). This demonstration includes the lower and upper corners of the uncertainty regions.

If you require any further assistance or have additional inquiries, please feel free to ask, or we can consider this issue resolved.

Omer.
